=== Helioviewer-Project/api/docroot/schema/client_state.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://api.helioviewer.org/schema/client_state.schema.json",
    "title": "Client State",
    "description": "State information used to initialize the helioviewer.org UI",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "date": { "type": "number" },
        "centerX": { "type": "number" },
        "centerY": { "type": "number" },
        "imageScale": { "type": "number" },
        "event_selections": {
            "$ref": "https://api.helioviewer.org/schema/event_selections.schema.json"
        },
        "event_visibility_selections": {
            "$ref": "https://api.helioviewer.org/schema/event_visibility_selections.schema.json"
        },
        "imageLayers": {
            "type": "array",
            "items": {
                "$ref": "https://api.helioviewer.org/schema/image_layer.schema.json"
            }
        },
        "celestialBodies": {
            "$ref": "https://api.helioviewer.org/schema/celestial_bodies.schema.json"
        },
        "enable3d": { "type": "boolean" }
    },
    "required": [
        "date",
        "centerX",
        "centerY",
        "imageScale",
        "event_selections",
        "event_visibility_selections",
        "imageLayers",
        "celestialBodies"
    ]
}

=== Helioviewer-Project/api/tests/unit_tests/validation/test_data/client_state/valid/valid_17.json
{
    "date": 1410269529000,
    "imageScale": 4.84088176,
    "centerX": -2894.0322215830834,
    "centerY": 101.72638697583727,
    "imageLayers": [
        {
            "end": "2024-07-29 17:33:45",
            "start": "2010-06-02 00:05:36",
            "opacity": 100,
            "visible": true,
            "diffTime": 1,
            "nickname": "AIA 171",
            "sourceId": 10,
            "uiLabels": [
                {
                    "label": "Observatory",
                    "name": "SDO"
                },
                {
                    "label": "Instrument",
                    "name": "AIA"
                },
                {
                    "label": "Measurement",
                    "name": "171"
                }
            ],
            "diffCount": 60,
            "Instrument": "AIA",
            "difference": 0,
            "Measurement": "171",
            "Observatory": "SDO",
            "baseDiffTime": "2024-07-19T13:28:50.000Z",
            "layeringOrder": 1
        }
    ],
    "event_selections": [
        "HEK>>Active Region>>HMI_SHARP",
        "HEK>>Active Region>>HMI SHARP",
        "HEK>>Active Region>>NOAA_SWPC_Observer",
        "HEK>>Active Region>>NOAA SWPC Observer",
        "HEK>>Active Region>>SPoCA",
        "HEK>>Coronal Cavity",
        "HEK>>Coronal Dimming",
        "HEK>>Coronal Hole>>SPoCA",
        "HEK>>Coronal Jet",
        "HEK>>CME",
        "HEK>>Coronal Rain",
        "HEK>>Coronal Wave",
        "HEK>>Emerging Flux>>Emerging_flux_region_module",
        "HEK>>Emerging Flux>>Emerging flux region module",
        "HEK>>Eruption",
        "HEK>>Filament",
        "HEK>>Filament Activation",
        "HEK>>Filament Eruption",
        "HEK>>Flare",
        "HEK>>Loop",
        "HEK>>Oscillation",
        "HEK>>Plage",
        "HEK>>Sigmoid>>Sigmoid_Sniffer",
        "HEK>>Sigmoid>>Sigmoid Sniffer",
        "HEK>>Spray Surge",
        "HEK>>Sunspot>>EGSO_SFC",
        "HEK>>Sunspot>>EGSO SFC",
        "HEK>>Topological Object>>SSW_PFSS_v2_\\+_null_point_finder_v20180808",
        "HEK>>Topological Object>>SSW PFSS v2 \\+ null point finder v20180808",
        "CCMC>>DONKI>>CME",
        "CCMC>>Solar Flare Predictions>>MAG4_LoS_FEr",
        "CCMC>>Solar Flare Predictions>>MAG4 LoS FEr"
    ],
    "event_visibility_selections": {
        "HEK": {
            "marker_visibility": true,
            "label_visibility": true
        },
        "CCMC": {
            "marker_visibility": true,
            "label_visibility": true
        },
        "RHESSI": {
            "marker_visibility": true,
            "label_visibility": true
        },
        "WSA": {
            "marker_visibility": true,
            "label_visibility": true
        }
    },
    "celestialBodies": {
        "soho": [],
        "stereo_a": [
            "stereo_a-mercury-tree-label"
        ],
        "stereo_b": []
    }
}

=== Helioviewer-Project/api/tests/unit_tests/validation/test_data/client_state/valid/valid_event_layer_name.json
{
    "date": 1712557812000,
    "centerX": -172.3873528481749,
    "centerY": -216.25766746329495,
    "imageScale": 0.60511022,
    "event_selections": [],
    "event_visibility_selections": {
        "HEK": {
            "marker_visibility": true,
            "label_visibility": true
        },
        "CCMC": {
            "marker_visibility": true,
            "label_visibility": true
        },
        "RHESSI": {
            "marker_visibility": true,
            "label_visibility": true
        },
        "WSA": {
            "marker_visibility": true,
            "label_visibility": true
        }
    },
    "imageLayers": [
        {
            "end": "2024-04-08 06:30:13",
            "start": "2024-04-08 06:19:24",
            "opacity": 35,
            "visible": true,
            "diffTime": 1,
            "nickname": "IRIS SJI 2796",
            "sourceId": 89,
            "uiLabels": [
                {
                    "name": "IRIS",
                    "label": "Observatory"
                },
                {
                    "name": "SJI",
                    "label": "Instrument"
                },
                {
                    "name": "2796",
                    "label": "Measurement"
                }
            ],
            "diffCount": 60,
            "Instrument": "SJI",
            "difference": 0,
            "Measurement": "2796",
            "Observatory": "IRIS",
            "baseDiffTime": "2024-06-12T08:32:57.000Z",
            "layeringOrder": 1
        },
        {
            "end": "2024-06-11 06:38:14",
            "start": "2012-07-05 00:09:05",
            "opacity": 100,
            "visible": "1",
            "diffTime": 1,
            "nickname": "AIA 1600",
            "sourceId": 15,
            "uiLabels": [
                {
                    "name": "SDO",
                    "label": "Observatory"
                },
                {
                    "name": "AIA",
                    "label": "Instrument"
                },
                {
                    "name": "1600",
                    "label": "Measurement"
                }
            ],
            "diffCount": 60,
            "Instrument": "AIA",
            "difference": 0,
            "Measurement": "1600",
            "Observatory": "SDO",
            "baseDiffTime": "2024-04-08T05:30:13.000Z",
            "layeringOrder": 1
        }
    ],
    "celestialBodies": {
        "soho": [
            "soho-mercury-tree-label",
            "soho-venus-tree-label",
            "soho-mars-tree-label",
            "soho-jupiter-tree-label",
            "soho-saturn-tree-label",
            "soho-uranus-tree-label",
            "soho-neptune-tree-label"
        ],
        "stereo_a": [
            "stereo_a-mercury-tree-label"
        ],
        "stereo_b": [
            "stereo_b-mercury-tree-label"
        ]
    }
}
